### PR TITLE
Allow setting VPN mode in plugin opts

### PR DESCRIPTION
**Pull request by zonyitoo**

### CODE REVIEW

**Comment by Mygod** [comment]
I don't think this is necessary. Why?

**Comment by madeye** [comment]
I think it can help align the behavior of VPN mode options across different implementations.

We'd like to pass 'V' option through plugin-ops rather than command line.

**Comment by madeye** [comment]
But it's a breaking change, as we are using -V or V to enable the VPN mode.

We may need to document it somewhere for plugin developers.

**Comment by Mygod** [comment]
I don't understand why we have to break this. Just keep the old behavior?

**Comment by madeye** [comment]
@zonyitoo mentioned that -V option maybe used for verbose logging or printing version number.

**Comment by zonyitoo** [comment]
Why is that a breaking change? `-V` command line option is still available.

**Comment by madeye** [comment]
Yeah, unless we remove the workaround in shadowsocks-rust, this change won't break anything.

Let's merge this PR and keep using 'vpn' option in the future.

**Comment by Mygod** [comment]
Does it already break any plugin? If not, let's keep using `-V` until somebody complains...

**Comment by Mygod** [comment]
A better way to do this is to keep the old behavior, and introduce plugin lib 2.0.0 and pass something like `vpn:protect_path` as an additional option if the plugin lib version is 2.+.

**Comment by zonyitoo** [comment]
I am still confused about why adding a `vpn` option is a breaking change?

**Comment by madeye** [comment]
Okay, I agree the "breaking change" is not precise here.

Just to make sure we would handle the backward compatibility problem properly.

Maybe @Mygod has a better idea.

**Comment by zonyitoo** [comment]
Users can keep using `-V` if they want to. This option is like the `fastOpen` option, you can also use `-fast-open` to enable it from command line.

**Comment by madeye** [comment]
Let's merge this for now. I didn't see any issue here

**Comment by Mygod** [comment]
Oh I was talking about what shadowsocks-android should pass to the plugin. I agree that `-V` is kind of ambiguous but to pass it in plugin_opts we need to make sure the plugin supports such behavior.

**Pull request merged**
