### PR TITLE
Shrink release binary size

### PR DESCRIPTION
**Pull request by linusyang**
The compiled binary is oversized due to the reference to the package `v2ray.com/ext/tools/conf`. This package links to almost every v2ray core package, which is not required in this plugin. By applying this patch, the compiled binary reduces from 15MB to 9MB on macOS.

In fact, we only need to use the `LogConfig` struct from `v2ray.com/ext/tools/conf/log.go` to specify the log level. But golang does not allow to refer to a single source file.

A quick dirty hack is to directly copy the `log.go` to this project (renamed to `logconf.go` in this patch). Also, this makes it possible to customize the logs. For example, there are a lot of access logs on the server side, even in the warning or error level. We can disable it by setting
```go
config.AccessLogType = log.LogType_None
```

### CODE REVIEW

**Comment by Mygod** [comment]
Well... Actually we only need to use that last switch in that file...

**Comment by linusyang** [comment]
@Mygod Sure. I think we can simplify it without including a new file.

**Comment by Mygod** [comment]
I wonder if there's a way to trim binary size though?

**Comment by linusyang** [comment]
The golang compiler will not trim unused functions, which may depend on large packages.

I think we could reduce the size by
* Stripping debug info by `-ldflags "-s -w"`. (already done in the release script)
* Reduce dependencies to large packages. (what this patch does)

The package dependency can be checked by tools like
https://github.com/KyleBanks/depth

**Pull request merged**
