### PR TITLE
Lots of changes proposed

### PR DESCRIPTION
**Pull request by Mygod**
:construction: Still work in progress :construction: 

@VictoriaRaymond Are these APIs used stable enough or is using JSON preferred?

### CODE REVIEW

**Comment by VictoriaRaymond** [comment]
Yes. Protobuf-based config is preferred, if the config is not exposed to end user.

**Comment by Mygod** [comment]
> Protobuf-based config is preferred

I'm assuming you're talking about the approach in this PR instead of JSON. Great.

Are these APIs documented anywhere though? I had to dig through your tests to figure out usages. Also any tips on debugging golang for newbies like me? :smile:

**Comment by Mygod** [comment]
@VictoriaRaymond I see there are 5 log levels. Are there any hooks for the log methods to customize its behavior on Android? (Android logcat supports log levels as well)

**Comment by VictoriaRaymond** [comment]
There are no much docs on protobuf def yet. Most of them are aligned with JSON config, or self explanatory. Please submit an issue or PR if you find some confusing.

There are two hooks for handling logs:

1. [common/log.RegisterHandler](https://github.com/v2ray/v2ray-core/blob/master/common/log/log.go#L40) with your own implementation of global log handler.
2. [app/log.RegisterHandlerCreator](https://github.com/v2ray/v2ray-core/blob/master/app/log/log_creator.go#L18) with your log handler for different level of logs.

**Comment by Mygod** [comment]
Well for starters, I personally find `core.Config` to be hella confusing. What goes under `App`? (I spent quite a while how to use it but I'm still unsure) Is `Transport` supposed to be a global config that can be overridden? How is `Extension` used?

**Comment by VictoriaRaymond** [comment]
Anything implements [features.Feature](https://github.com/v2ray/v2ray-core/blob/master/features/feature.go#L9) interfaces go to `App`. All V2Ray embedded features are in `app/` folder.

`Transport` is now deprecated. You may use `receiver_settings` and `sender_settings` in `InboundHandlerConfig` and `OutboundHandlerConfig`.

`Extension` is not used by V2Ray. It is used by some other third party apps.

**Comment by VictoriaRaymond** [comment]
[Dispatcher](https://github.com/v2ray/v2ray-core/blob/master/features/routing/dispatcher.go#L15) is a feature that chooses an outbound for each inbound connections. It happens to have no config (so far) in V2Ray. On the other hand, V2Ray enables a feature only when the config of that feature is specified. This means you can write your own Dispatcher, and enable it by putting its config into `App`. The default Dispatcher will not be enabled in this case.

Same as [inbound.Manager](https://github.com/v2ray/v2ray-core/blob/master/features/inbound/inbound.go#L26) and outbound.Manager.

@xiaokangwang for the usage of `Extension`.

**Comment by Mygod** [comment]
@madeye Everything is in perfect working condition (http, tls, quic) now, except I haven't started working on Android part yet. Feel free to check it out. You can check commit log for a list of changes.

@VictoriaRaymond QUIC seems to perform really poorly when concurrency > 1. Did you use QUIC's native multiplexing or did you treat QUIC as a TCP-like stream and use it to multiplex? The first one should be used as QUIC operates over UDP. Also doing multiplexing for WebSocket seems quite unnecessary so I disabled it by default.

**Comment by VictoriaRaymond** [comment]
It is not necessary to combine Mux with Quic, as Quic has its only multiplexing functionality. However, your experience with concurrency may be caused by Quic itself (see https://github.com/v2ray/v2ray-core/issues/1503)

**Comment by Mygod** [comment]
Hmm, does QUIC internally handle connection reuse as well so that we can just disable mux completely?

**Comment by VictoriaRaymond** [comment]
If your cert is valid, it gets auto validated against system root. It should always pass the check. To invalidate your cert issued from acme, you need to remove the corresponding CA from your system root at client.

The 'verify' functionality is designed to use with custom CA. Both server and client use the same self-signed CA cert. The server will auto-issue a leaf cert for every incoming domain, derived from the CA, and client verify the leaf cert against the self-signed CA.

**Comment by Mygod** [comment]
I see. It seems like I have misunderstood the purpose of that functionality. Do you think it's useful to implement an extra check on the public key even if the certificate has been verified by the system?

**Comment by VictoriaRaymond** [comment]
I doubt its usefulness. There is no way to capture or verify such behavior conducted by a CA. Issuing a certificate to hijack proxy connections is a very targeted scenario. It is not likely that such behavior gets exposed to other monitoring system, such as Chrome and Firefox. This makes difficult for users and developers to use the blacklist functionality.

**Comment by Mygod** [comment]
> I doubt its usefulness. There is no way to capture or verify such behavior conducted by a CA. Issuing a certificate to hijack proxy connections is a very targeted scenario. It is not likely that such behavior gets exposed to other monitoring system, such as Chrome and Firefox. This makes difficult for users and developers to use the blacklist functionality.

Hmm, I didn't understand what you're trying to say. :sweat_smile:

**Comment by VictoriaRaymond** [comment]
Basically it is hard to tell when to blacklist a CA, and when to remove a CA from the blacklist. It is a valid feature. But we have to put something in the doc like: "we implemented this feature, but we don't really know when to use it".

**Comment by Mygod** [comment]
I was actually suggesting a white-list instead of a black-list. Basically, this removes the need of a trusted key-store. The client simply verifies that signature chain the server sends contains all the public keys listed in the white-list. In that case, in order to perform a MitM, the adversary needs to compromise every public key in the white-list (instead of any key in the trusted key-store).

**Comment by VictoriaRaymond** [comment]
It is possible to skip system root, and only use user-provides certs for verification. You can submit a feature request for this. Technical-wise Golang doesn't allow partial loading of system root. Users may have to provide CAs on their own.

**Pull request merged**
