### PR TITLE
Use modules for reproducible builds

### PR DESCRIPTION
**Pull request by Mygod**
Requires go1.11. Read more: https://github.com/golang/go/wiki/Modules

@VictoriaRaymond I think it would be great if v2ray/core and v2ray/ext adapt this as well.

@madeye We should probably do this for shadowsocks-android as well. I can see overture is getting updated with each releases, but no changes can be found in shadowsocks-android.  
Also let's use semantic version as required by modules. Using date as version name is terrible IMO.

### CODE REVIEW

**Comment by VictoriaRaymond** [comment]
V2Ray doesn't adopt go modules, as it conflicts with our development mode. In Go modules, a developer has to focus on a single repo at a time. All dependencies are downloaded into a "cache" directory. However, V2Ray uses two repos (core and ext). The module design brings only difficult for our development, but no benefit. We are waiting Go 1.12 to see if there is any improvements in the module design.

**Comment by Mygod** [comment]
If core and ext reference each other, maybe it's better to merge them into one repo?

**Comment by Mygod** [comment]
If core and ext reference each other, maybe it's better to merge them into one repo?

**Comment by VictoriaRaymond** [comment]
No. ext depends on core, but not the other direction. ext has relatively low quality, and may contain experimental code, etc.

**Comment by Mygod** [comment]
Oh no there's also dirty changes in lucas-clemente/quic-go... What have you done...

I guess do not merge yet then.

**Comment by VictoriaRaymond** [comment]
Mostly for memory management. V2Ray has some special logic to avoid necessary copy of buffers.

**Comment by Mygod** [comment]
Any chance you can get them merged back to upstream?

**Comment by VictoriaRaymond** [comment]
What we can do is, instead of using `vendor` directory (which causes `go mod` to generate indirect dependencies), we can simply use a hard copy (say 'external' directory) for all dependencies. 

Go module has made many things more complicated than they are supposed to be.

**Comment by VictoriaRaymond** [comment]
Updated. Now quic-go and websocket deps go away in your go.mod file.

**Comment by Mygod** [comment]
Wow thanks for the hard work! I honestly didn't think you would actually fix this. I'll give it a spin soon.

Personally, I find reproducible builds useful when using `git bisect` to check out historical builds for debugging (of course it's rare to encounter such bugs). The current `go get` procedure renders this virtually useless as `go build` will keep using the up-to-date dependencies. This dependency management also makes it easier to integrate a go git submodule outside of `$GOPATH`, for example, see https://github.com/shadowsocks/shadowsocks-android/pull/2079.

**Comment by Mygod** [comment]
Awesome. Everything works perfectly now.

@madeye Circle CI is also added. Clean build takes 1:15 and with cache 1:01 with binaries uploading. (10 platforms without upx) I say it's ready to merge.

**Pull request merged**
